services:
  sveapark:
    build: .
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - cloudflared
networks:
  cloudflared:
    external: true # Uses an existing network
